Feature/init-design
hcheng826/arc-contracts pull request #1
Opened 2023-03-12 02:45 UTC by hcheng826

WIP, open PR to have in-line comments to discuss

2023-03-14 11:39 UTC, JaisPiyush requested changes
Remove the oracle contract completely and LoadAgent, and LoanAgentFactory should be finalized names

2023-03-14 11:40 UTC, JaisPiyush approved these changes

2023-03-16 15:39 UTC, JaisPiyush requested changes

2023-03-16 15:39 UTC, JaisPiyush commented on src/LoanAgentFactory.sol
> +        _;
Add oracle contract address
```solidity
address public immutable oracle;
```
and check msg.sender is equal to this address in the modifier

2023-03-16 15:39 UTC, JaisPiyush commented on src/LoanAgentFactory.sol
> +    enum LoanRequestStatus{ PENDING, APPROVED, REJECTED }
LoanAgentFactory which manages all the LoanAgent. This enum has no use.

2023-03-16 15:39 UTC, JaisPiyush commented on src/LoanAgent.sol
> +        WaitingForOracleVerifiction,
Add another status `WaitingForPleding`. This status indicated that all the validations are done and only the node is required to call pledge command from the cli.

2023-03-16 15:39 UTC, JaisPiyush commented on src/LoanAgent.sol
> +        WaitingForOracleVerifiction,
I'll add the status in the issue

2023-03-16 15:39 UTC, JaisPiyush commented on src/LoanAgent.sol
> +    function withdrawMinerEarning(uint256 amount) external onlyRealOwner {}
But msg.sender will be an `address` let us confirm the address spec first.

2023-03-17 01:03 UTC, hcheng826 commented on src/LoanAgentFactory.sol
> +        _;
just a placeholder to make it compile, will impl later

2023-03-17 01:04 UTC, hcheng826 commented on src/LoanAgent.sol
> +        WaitingForOracleVerifiction,
updated

2023-03-17 14:14 UTC, JaisPiyush requested changes

2023-03-17 14:14 UTC, JaisPiyush commented on src/aFIL.sol
> +    modifier onlyOracle() {
Oracle should not update the stat of aFIL directly. Instead LoanAgentFactory should have these privileges. replace `onlyOracle` with `onlyLoanAgentFactory`

2023-03-17 14:16 UTC, JaisPiyush requested changes

2023-03-17 14:16 UTC, JaisPiyush commented on src/aFIL.sol
> +        uint totalAmount;
aFIL contract will only manage aFIL:FIL pool and should not have any kind of relation with LoanAgents or other things.

Loan and loans should be moved to LoanAgentFactory, as it holds power to create and manage them.

2023-03-17 14:16 UTC, JaisPiyush commented on src/aFIL.sol
> +        uint totalAmount;
Only maintain the total loan amount

2023-03-17 15:11 UTC, JaisPiyush approved these changes
Merging this pull request in main. Then I will begin working on the Oracle contract and LoanAgentFactory contract (oracle side)

2023-03-17 15:12 UTC, merged